server {
    listen 80;
    server_name localhost;

    # ログの設定（ボットの大量アクセスをFlaskに流さないための盾になります）
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        proxy_pass http://app:5000; # Docker内部ネットワーク経由でFlask(app)に転送
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}